### ISSUE TITLE
::Fixnum is deprecated

### ISSUE THREAD

**Issue by valvin1** [sjbach/lusty#111]
Hi,
I've just updated to kubuntu 18.04 and now there is ruby 2.4 which has deprecated ::Fixnum.

It looks like you have fixed it in this [commit](https://github.com/sjbach/lusty/commit/dcfe72e90e835ec89bbe2a0f863e664450d848e)

I am installing Lusty using vundle and it looks it doesn't take this update?

Thank you :)

**Comment by sjbach** [comment]
Hi, I don't use Vundle, but I bet if you set the `Plugin` line for lusty in your `.vimrc` to use this Github repository, it'll install the newest version.  But I should probably update the release on vim.org anyway (which is what I think you're getting).

**Comment by sjbach** [comment]
Okay, there are new "official" releases on https://www.vim.org/scripts.  The http://vim-scripts.org scraper should pick them up by tomorrow and that should allow Vundle to see them.  :thumbsup:

**Comment by valvin1** [comment]
Thank you :)
