### ISSUE TITLE
Ruby not detected

### ISSUE THREAD

**Issue by schyzophrene-asynchrone** [sjbach/lusty#113]
When I start vim (and load lusty explorer) I have this error:
```
Sorry, LustyJuggler requires ruby.  Here are some tips for adding it:

Debian / Ubuntu:
    # apt-get install vim-ruby

Fedora:
    # yum install vim-enhanced

Gentoo:
    # USE="ruby" emerge vim

FreeBSD:
    # pkg_add -r vim+ruby

Windows:
    1. Download and install Ruby from here:
       http://www.ruby-lang.org/
    2. Install a Vim binary with Ruby support:
       http://segfault.hasno.info/vim/gvim72.zip

Manually (including Cygwin):
    1. Install Ruby.
    2. Download the Vim source package (say, vim-7.0.tar.bz2)
    3. Build and install:
         # tar -xvjf vim-7.0.tar.bz2
         # ./configure --enable-rubyinterp
         # make && make install

(If you just wish to stifle this message, set the following option:
  let g:LustyJugglerSuppressRubyWarning = 1)
```

Which makes me think vim has not been compiled with ruby support.
However, typing `vim --version` does allow me to check that I *have* ruby support.

I’ve recently updated ruby on my computer (and that’s probably where the error comes), I now have ruby 2.6.0-4 installed on it.
I’ve already had this issue and all I had to do last time was to update LustyExplorer. I can’t to that this time since I’m up to date. ^^
Any idea how to correct this ?

**Comment by sjbach** [comment]
Most likely Vim can't see Ruby anymore, for whatever reason. What do you get when you run `:echo has('ruby')` in a fresh Vim session?

**Comment by schyzophrene-asynchrone** [comment]
I get 0.
Should I see this with the package maintainer ?

**Comment by schyzophrene-asynchrone** [comment]
I checked: vim was compiled with ruby 2.5 support (running `:ruby 1` in a vim session, I get `Konnte Bibliothek libruby.so.2.5 nicht laden`), but I have ruby 2.6 on my computer. I guess vim should be compiled again, which I will see with the package maintainer.

**Comment by sjbach** [comment]
Thanks for the update. :+1: I'll close this issue for now, but feel free to re-open if it does end up to be a plugin problem.
