### ISSUE TITLE
Conflicts with key bindings from paredit mode in slimv

### ISSUE THREAD

**Issue by achin** [sjbach/lusty#60]
I have the latest development version of lusty-juggler installed along side paredit.vim from slimv 0.93. I think there might be some key binding conflicts between the two plugins. The "s" and "d" bindings don't work as expected after I've started lj.

When I press "s", vim changes to insert mode and inserts ":call <SNR>17_LustyJugglerKeyPressed('{key}')" whenever any of lj's keybindings are pressed.

When I press "d", vim doesn't do anything, but subsequent presses delete a character in the buffer.

I'm using MacVim 7.3 (Snapshot 61) on OS X. Please let me know if there's anything I can do to help you debug this problem.

**Comment by sjbach** [comment]
Thanks.  I think this would have been fixed in be929b3c6edb8e7c059d1e44849fcf0db325e48d.
