### ISSUE TITLE
Conflicts with vim-yankstack and YankRing

### ISSUE THREAD

**Issue by kshenoy** [sjbach/lusty#77]
The commands `d` and `s` (maybe others, but this is all I know so far) stop working as expected after LustyJuggler is invoked. Some commands like `d0`, `d$` etc. work fine but `dd` doesn't work at all. I'm seeing this problem only when I use LustyJuggler along with [Yankstack](https://github.com/vim-scripts/yankstack) or YankRing(https://github.com/vim-scripts/YankRing.vim).

I think it may be due to conflicting mappings (or function calls) but I could be wrong.

**Comment by sjbach** [comment]
I think/hope this was fixed in be929b3c6edb8e7c059d1e44849fcf0db325e48d.
